name: Run Unit Tests

on:
  push:
    # branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.9', '3.11', '3.12']
        exclude:
          - os: ubuntu-latest
            python-version: '3.7'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # configure python
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install required system libraries
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install libopengl0 libglu1-mesa -y
      # install deps
      - name: Install dependencies for ${{ matrix.os }} Python ${{ matrix.python-version }}
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      # find and run all unit tests
      - name: Run unit tests
        run: python -m unittest discover -s tests
